### PR TITLE
created 'PD-72 Members Card', 'PD-75 Industry Card' and 'PD-74 Location Card' and refined the code

### PR DESCRIPTION
**Pull request by yuangao0317**
### Implemented:
PD-72 Members Card:
Bar Chart, Autocomplete Search Bar, PDF export, Fake data
PD-75 Industry Card:
Bar Chart, Autocomplete Search Bar, PDF export, Fake data
PD-74 Location Card:
Pie Chart, Autocomplete Search Bar, PDF export, Fake data

### Optimized:
Added 'Context',
Optimized code structure

### Need to be fixed:
Routes, 
Fetching data from Firestore

### CODE REVIEW

**Comment by mpa-mxiang** [comment]
image

I am trying to review this but from the screenshot, there is not much I can view.

**Comment by YuanGao0317** [comment]
they are on different routes. 
<Routes>
        <Route path="/" element={<Home />} />

        <Route path="/members" element={<MembersCardRefine />} />
        <Route path="/industry" element={<IndustryCardRefine />} />
        <Route path="/location" element={<LocationCardRefine />} />
      </Routes>

**Comment by yuangao0317** [comment]
> image
> I am trying to review this but from the screenshot, there is not much I can view.

Try different routes.
```
<Routes>
        <Route path="/" element={<Home />} />

        <Route path="/members" element={<MembersCardRefine />} />
        <Route path="/industry" element={<IndustryCardRefine />} />
        <Route path="/location" element={<LocationCardRefine />} />
</Routes>
```

**Comment by yuangao0317** [comment]
> image
> I am trying to review this but from the screenshot, there is not much I can view.

If you want to test the search bar functionality, you can find the data in 'developer console', and these are fake data.
image

**Pull request merged**
